### ISSUE TITLE
no registered parsers error

### ISSUE THREAD

**Issue by mangoman6** [mattdesl/canvas-sketch#152]
since updating to monterey 12.3.1 and updating canvas-sketch to it's latest version, i get the following errors. i'm on a 2015 macbook pro

`/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/snapdragon/lib/parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

Error: no parsers registered for: "]"
    at parse (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/snapdragon/lib/parser.js:473:15)
    at Parser.parse (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/snapdragon/lib/parser.js:477:24)
    at Snapdragon.parse (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/snapdragon/index.js:122:28)
    at Snapdragon.<anonymous> (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/braces/lib/braces.js:40:45)
    at Braces.parse (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/braces/lib/braces.js:66:26)
    at Braces.expand (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/braces/lib/braces.js:87:18)
    at create (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/braces/index.js:142:15)
    at memoize (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/braces/index.js:298:13)
    at Function.braces.create (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/braces/index.js:165:10)
    at Function.braces.expand (/usr/local/lib/node_modules/canvas-sketch-cli/node_modules/braces/index.js:81:17)

Node.js v17.3.0`

**Comment by mangoman6** [comment]
today a reinstall of canvas-sketch fixed the issue
