### ISSUE TITLE
Error: spawn EINVAL

### ISSUE THREAD

**Issue by pavel-101** [mattdesl/canvas-sketch#199]
Hi, 

I'm really new to coding so please bare with me. :) 
I just installed canvas-sketch and node.js. When I trying to create a new sketch with canvas-sketch i get: 
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at command (C:\Sketches\node_modules\spawn-npm-install\index.js:45:14)
    at Array.<anonymous> (C:\Sketches\node_modules\install-if-needed\index.js:47:9)
    at runSeries (C:\Sketches\node_modules\run-series\index.js:23:33)
    at run (C:\Sketches\node_modules\install-if-needed\index.js:52:5)
    at C:\Sketches\node_modules\read-closest-package\index.js:29:7

I'm running on:
Windows 11 Home
node v20.12.2
npm 10.5.0

Tried:
The suggestion in this [post](https://github.com/mattdesl/canvas-sketch/issues/179#issuecomment-1413439451)
Install globally, run with npx and --save-dev.
All attempts gives same result,
 
After searching a bit more i came across this [post](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2) which talks about a security update to node. I wonder if this is what's causing the issue? If not how, can i get it to work?

**Comment by SonoDavid** [comment]
You can fix it by going to `C:\Sketches\node_modules\spawn-npm-install\index.js` and changing the lines 36 to 40 to this:

```javascript
  var spawnArgs = {
    shell: true,
    cwd: opt.cwd,
    env: opt.env || process.env,
    stdio: opt.stdio
  }
``` 

adding shell: true to the parameters.

I seems like the folder was downloaded from this repo: [https://github.com/mattdesl/spawn-npm-install](spawn-npm-install).

**Comment by pavel-101** [comment]
Thank you @SonoDavid for your help, it worked!

**Comment by glynnboyd** [comment]
Hi! I am also very new to coding and CMD in general. I am also having this issue (exact same word for word) when I try to create a new sketch with canvas-sketch. I have also tried the shell: true fix via VSC and it still doesn't work.

Win 10 Home
node v20.13.1
npm 10.5.2

Are you able to help please?

**Comment by Eidan78** [comment]
how do I fix this? I have no node_modules folder at all...

**Comment by Dellangelo-graphic** [comment]
Hi, I've got the same problem but with one exception: I don't have the note_modules folder :(
I don't know why the program didn't create that. I'm also new in coding please help :(
Thank you anticipated!

**Comment by mattdesl** [comment]
Hey all, I've just changed a feature that may help fix this problem even when node version is >= 18. Unfortunately I don't have access to Windows right now to test.

Can you try updating the CLI?

If you are using it globally:

```js
npm i canvas-sketch-cli@1.15.0 --global

mkdir test-sketch
cd test-sketch
canvas-sketch sketch.js --new
```

Or if you are using it with `npx`:

```js
mkdir test-sketch
cd test-sketch
npx canvas-sketch-cli@1.15.0 sketch.js --new
```

Or if you are using it with locally installed devDependency:

```js
mkdir test-sketch
cd test-sketch
npm init -y

npm install canvas-sketch-cli@1.15.0 --save-dev
npx canvas-sketch sketch.js --new
```
