### ISSUE TITLE
Throws error when using `canvas-sketch --new --open`

### ISSUE THREAD

**Issue by prakhar625** [mattdesl/canvas-sketch#26]
config:
❯ node -v
v11.0.0

❯ npm -v
6.4.1

the error is :
```
❯ canvas-sketch --new --open
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/magops/.nvm/versions/node/v11.0.0/lib/node_modules/canvas-sketch-cli/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

**Comment by mattdesl** [comment]
This was a bug upstream.

https://github.com/isaacs/node-graceful-fs/issues/139

Can you try installing globally again?
