### ISSUE TITLE
TypeError: promisify is not a function

### ISSUE THREAD

**Issue by vishalkumarlondon** [mattdesl/canvas-sketch#39]
Hey Matt! After completing the last installation step: 

_# Scaffold a new 'sketch.js' file and open the browser_
canvas-sketch sketch.js --new --open

I get the following Error:

/usr/local/lib/node_modules/canvas-sketch-cli/src/util.js:10
const readFile = promisify(fs.readFile);
                 ^

TypeError: promisify is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/canvas-sketch-cli/src/util.js:10:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/canvas-sketch-cli/src/index.js:14:66)
    at Module._compile (module.js:571:32)

Not sure why?

I completed the first three steps:

_# Install the CLI tool globally_
npm install canvas-sketch-cli -g

_# Make a new folder to hold all your generative sketches_
mkdir my-sketches

_# Move into that folder_
cd my-sketches

**Comment by vishalkumarlondon** [comment]
Yep, it worked a treat, many thanks! FYI, I followed [this](https://stackoverflow.com/questions/11284634/upgrade-node-js-to-the-latest-version-on-mac-os) advice on StackOverflow
