### ISSUE TITLE
Yarn 2 support

### ISSUE THREAD

**Issue by allforabit** [mattdesl/canvas-sketch#85]
I'm just trying out the project after watching some of the frontend masters course. It looks really good to just get up and running quickly. I'm just wondering if it supports yarn 2. After a quick test I'm getting the following error:
```
[0004] info  Server running at http://192.168.1.6:9966/ (connect)
[0004] info  LiveReload running
Error: Cannot find module 'canvas-sketch' from 'sketch.js'
    at Local\Yarn\Data\global\node_modules\esmify\esmify.js:47:19
    at \Local\Yarn\Data\global\node_modules\browser-resolve\index.js:265:24        
    at \Local\Yarn\Data\global\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:14
    at process (\Local\Yarn\Data\global\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (\Local\Yarn\Data\global\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (\Local\Yarn\Data\global\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (\Local\Yarn\Data\global\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at \Local\Yarn\Data\global\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (fs.js:158:21) {
  stream: [Labeled]
```
The reason I ask is I have the new yarn a spin and it seems like a vast improvement on speed and drive space usage.

Anyway great project, and I am really enjoying the course.

**Comment by allforabit** [comment]
Actually just tested and it works fine with yarn 1 so have updated the issue.
